insert into Coaches (user_id, specialization, terminator) values (1, 'Youth Fitness', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (2, 'Strength & Conditioning', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (3, null, 'active');
insert into Coaches (user_id, specialization, terminator) values (4, 'Weight Loss', 'active');
insert into Coaches (user_id, specialization, terminator) values (5, 'Strength & Conditioning', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (6, 'Group Fitness', null);
insert into Coaches (user_id, specialization, terminator) values (7, 'Corrective Exercise', 'active');
insert into Coaches (user_id, specialization, terminator) values (8, 'Strength & Conditioning', 'active');
insert into Coaches (user_id, specialization, terminator) values (9, 'Strength & Conditioning', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (10, 'Group Fitness', 'active');
insert into Coaches (user_id, specialization, terminator) values (11, 'Sports Performance', 'active');
insert into Coaches (user_id, specialization, terminator) values (12, 'Weight Loss', 'active');
insert into Coaches (user_id, specialization, terminator) values (13, 'Sports Performance', 'active');
insert into Coaches (user_id, specialization, terminator) values (14, 'Sports Performance', 'active');
insert into Coaches (user_id, specialization, terminator) values (15, 'Nutrition Coaching', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (16, null, 'inactive');
insert into Coaches (user_id, specialization, terminator) values (17, 'Nutrition Coaching', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (18, 'Nutrition Coaching', 'active');
insert into Coaches (user_id, specialization, terminator) values (19, 'Weight Loss', 'active');
insert into Coaches (user_id, specialization, terminator) values (20, 'Senior Fitness', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (21, null, 'active');
insert into Coaches (user_id, specialization, terminator) values (22, 'Senior Fitness', 'active');
insert into Coaches (user_id, specialization, terminator) values (23, 'Senior Fitness', 'active');
insert into Coaches (user_id, specialization, terminator) values (24, 'Youth Fitness', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (25, 'Group Fitness', 'active');
insert into Coaches (user_id, specialization, terminator) values (26, 'Senior Fitness', null);
insert into Coaches (user_id, specialization, terminator) values (27, 'Sports Performance', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (28, 'Senior Fitness', 'active');
insert into Coaches (user_id, specialization, terminator) values (29, 'Senior Fitness', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (30, 'Strength & Conditioning', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (31, 'Group Fitness', 'active');
insert into Coaches (user_id, specialization, terminator) values (32, 'Strength & Conditioning', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (33, 'Senior Fitness', 'active');
insert into Coaches (user_id, specialization, terminator) values (34, 'Group Fitness', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (35, 'Weight Loss', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (36, 'Weight Loss', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (37, 'Nutrition Coaching', 'active');
insert into Coaches (user_id, specialization, terminator) values (38, 'Strength & Conditioning', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (39, 'Weight Loss', 'inactive');
insert into Coaches (user_id, specialization, terminator) values (40, 'Nutrition Coaching', 'inactive');
