insert into Dietitians (user_id, license_number, specialization) values (41, 'SM-13-DYH-928', 'Pediatric Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (42, 'SP-93-WIQ-560', 'Clinical Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (43, 'PA-35-LCH-284', 'Weight Management');
insert into Dietitians (user_id, license_number, specialization) values (44, 'FL-88-QJN-012', 'Pediatric Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (45, 'GG-71-GFB-641', 'Clinical Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (46, null, 'Weight Management');
insert into Dietitians (user_id, license_number, specialization) values (47, 'LH-51-VYI-838', 'Gerontological Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (48, 'ME-96-VLM-627', 'Weight Management');
insert into Dietitians (user_id, license_number, specialization) values (49, 'AQ-03-IPY-029', 'Gerontological Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (50, 'KU-73-BCM-447', 'Pediatric Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (51, 'UO-86-GQH-818', 'Gerontological Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (52, 'IW-09-NIR-201', 'Clinical Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (53, 'PE-66-EDM-323', 'Gerontological Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (54, null, 'Clinical Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (55, 'VR-66-SXG-773', 'Gerontological Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (56, null, 'Clinical Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (57, 'LD-02-ETM-432', 'Weight Management');
insert into Dietitians (user_id, license_number, specialization) values (58, 'CM-76-SWP-096', 'Weight Management');
insert into Dietitians (user_id, license_number, specialization) values (59, 'BG-12-SWW-353', 'Pediatric Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (60, 'ZU-89-EWU-463', 'Weight Management');
insert into Dietitians (user_id, license_number, specialization) values (61, null, 'Gerontological Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (62, 'CP-43-VED-673', null);
insert into Dietitians (user_id, license_number, specialization) values (63, 'JH-44-YGT-873', 'Clinical Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (64, 'IU-58-HKZ-554', null);
insert into Dietitians (user_id, license_number, specialization) values (65, 'CH-96-JZP-496', 'Sports Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (66, 'MT-50-FSV-012', 'Clinical Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (67, 'YJ-04-TWW-106', 'Pediatric Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (68, 'YQ-20-NIO-254', 'Weight Management');
insert into Dietitians (user_id, license_number, specialization) values (69, null, 'Weight Management');
insert into Dietitians (user_id, license_number, specialization) values (70, null, 'Clinical Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (71, 'OT-67-KGQ-384', 'Clinical Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (72, null, 'Gerontological Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (73, 'YJ-42-QWU-469', 'Pediatric Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (74, 'JH-10-BWO-054', null);
insert into Dietitians (user_id, license_number, specialization) values (75, 'HL-31-NDZ-189', null);
insert into Dietitians (user_id, license_number, specialization) values (76, 'IE-55-DEY-368', null);
insert into Dietitians (user_id, license_number, specialization) values (77, null, 'Clinical Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (78, 'IG-74-FBF-448', null);
insert into Dietitians (user_id, license_number, specialization) values (79, 'BB-22-ZQT-518', 'Pediatric Nutrition');
insert into Dietitians (user_id, license_number, specialization) values (80, 'KC-88-NUX-662', 'Sports Nutrition');
