insert into MealLogs (user_id, meal_date, meal_type, notes) values (38, '02/01/2025', 'breakfast', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (8, '10/18/2025', 'lunch', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (62, '11/06/2025', 'lunch', 'Snacked on some fresh fruit in the afternoon');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (157, '08/23/2025', 'snack', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (118, '10/12/2025', 'breakfast', 'Enjoyed a delicious salad for lunch');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (49, '01/14/2025', 'snack', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (55, '08/16/2025', 'breakfast', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (111, '06/19/2025', 'dinner', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (42, '05/31/2025', 'lunch', 'Enjoyed a delicious salad for lunch');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (99, '04/10/2025', 'lunch', null);
insert into MealLogs (user_id, meal_date, meal_type, notes) values (84, '09/07/2025', 'lunch', null);
insert into MealLogs (user_id, meal_date, meal_type, notes) values (57, '07/12/2025', 'dinner', 'Enjoyed a delicious salad for lunch');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (95, '03/08/2025', 'snack', 'Enjoyed a delicious salad for lunch');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (83, '07/12/2025', 'dinner', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (119, '05/03/2025', 'dinner', 'Enjoyed a delicious salad for lunch');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (16, '07/11/2025', 'dinner', 'Enjoyed a delicious salad for lunch');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (108, '06/13/2025', 'dinner', 'Snacked on some fresh fruit in the afternoon');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (14, '09/13/2025', 'snack', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (61, '04/10/2025', 'lunch', 'Enjoyed a delicious salad for lunch');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (147, '12/14/2024', 'dinner', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (157, '02/26/2025', 'snack', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (144, '05/28/2025', 'breakfast', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (28, '02/27/2025', 'dinner', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (71, '03/15/2025', 'snack', 'Snacked on some fresh fruit in the afternoon');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (24, '12/12/2024', 'snack', 'Snacked on some fresh fruit in the afternoon');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (160, '02/02/2025', 'breakfast', null);
insert into MealLogs (user_id, meal_date, meal_type, notes) values (151, '12/14/2024', 'breakfast', 'Snacked on some fresh fruit in the afternoon');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (22, '02/28/2025', 'snack', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (71, '05/12/2025', 'dinner', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (105, '05/23/2025', 'dinner', 'Snacked on some fresh fruit in the afternoon');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (32, '04/17/2025', 'snack', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (34, '08/14/2025', 'dinner', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (133, '05/11/2025', 'breakfast', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (88, '02/16/2025', 'snack', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (105, '10/19/2025', 'breakfast', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (22, '01/07/2025', 'breakfast', 'Snacked on some fresh fruit in the afternoon');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (120, '05/04/2025', 'breakfast', null);
insert into MealLogs (user_id, meal_date, meal_type, notes) values (121, '11/27/2025', 'dinner', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (132, '02/26/2025', 'snack', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (47, '09/23/2025', 'lunch', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (122, '08/05/2025', 'dinner', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (117, '01/12/2025', 'breakfast', null);
insert into MealLogs (user_id, meal_date, meal_type, notes) values (86, '03/13/2025', 'breakfast', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (78, '09/04/2025', 'breakfast', 'Snacked on some fresh fruit in the afternoon');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (120, '09/22/2025', 'breakfast', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (121, '01/26/2025', 'lunch', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (60, '11/15/2025', 'breakfast', null);
insert into MealLogs (user_id, meal_date, meal_type, notes) values (78, '10/09/2025', 'snack', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (87, '03/20/2025', 'snack', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (64, '06/02/2025', 'lunch', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (7, '03/22/2025', 'breakfast', 'Snacked on some fresh fruit in the afternoon');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (140, '09/02/2025', 'lunch', 'Snacked on some fresh fruit in the afternoon');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (4, '05/18/2025', 'lunch', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (57, '05/21/2025', 'lunch', 'Enjoyed a delicious salad for lunch');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (21, '03/11/2025', 'lunch', 'Enjoyed a delicious salad for lunch');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (132, '04/29/2025', 'snack', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (71, '12/20/2024', 'lunch', 'Snacked on some fresh fruit in the afternoon');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (160, '11/21/2025', 'dinner', 'Enjoyed a delicious salad for lunch');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (36, '10/19/2025', 'dinner', 'Enjoyed a delicious salad for lunch');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (114, '09/23/2025', 'dinner', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (158, '05/11/2025', 'dinner', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (100, '03/27/2025', 'dinner', 'Enjoyed a delicious salad for lunch');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (127, '10/23/2025', 'lunch', 'Snacked on some fresh fruit in the afternoon');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (138, '10/20/2025', 'snack', 'Indulged in a decadent dessert after dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (90, '09/21/2025', 'dinner', 'Tried a new recipe for dinner');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (56, '08/01/2025', 'lunch', null);
insert into MealLogs (user_id, meal_date, meal_type, notes) values (56, '08/06/2025', 'breakfast', null);
insert into MealLogs (user_id, meal_date, meal_type, notes) values (103, '05/16/2025', 'breakfast', 'Snacked on some fresh fruit in the afternoon');
insert into MealLogs (user_id, meal_date, meal_type, notes) values (87, '05/09/2025', 'snack', null);
insert into MealLogs (user_id, meal_date, meal_type, notes) values (40, '12/31/2024', 'dinner', 'Tried a new recipe for dinner');
