insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (104, null, 'info', '8/31/2025', 'Information: System update available');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (117, 'high', 'debug', '2/4/2025', 'Error: Database connection lost');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (102, 'critical', 'warning', '5/10/2025', 'Error: Database connection lost');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (89, 'low', 'debug', '7/21/2025', 'Warning: High CPU usage detected');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (83, 'critical', 'critical', '12/26/2024', 'Error: Database connection lost');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (104, 'high', 'debug', '3/16/2025', 'Information: System update available');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (101, 'low', 'critical', '10/23/2025', 'Warning: High CPU usage detected');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (102, 'critical', 'info', '7/14/2025', 'Error: Database connection lost');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (83, 'low', 'error', '11/30/2025', 'Information: System update available');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (92, 'medium', 'critical', '5/31/2025', 'Warning: High CPU usage detected');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (113, 'high', 'info', '2/24/2025', 'Warning: High CPU usage detected');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (104, 'low', 'debug', '4/1/2025', null);
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (96, 'low', 'info', '2/7/2025', 'Error: Database connection lost');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (105, 'critical', 'error', '8/18/2025', 'Critical alert: Server down');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (92, 'low', 'error', '10/21/2025', 'Error: Database connection lost');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (89, 'high', null, '4/8/2025', 'Warning: High CPU usage detected');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (91, 'critical', null, '3/5/2025', 'Information: System update available');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (90, 'medium', 'critical', '3/15/2025', 'Critical alert: Server down');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (114, 'high', 'info', '3/22/2025', 'Information: System update available');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (114, 'medium', 'debug', '8/1/2025', 'Information: System update available');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (101, 'medium', 'error', '6/6/2025', 'Error: Database connection lost');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (119, 'low', 'info', '9/22/2025', 'Critical alert: Server down');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (115, 'low', 'warning', '2/14/2025', 'Warning: High CPU usage detected');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (102, 'medium', 'error', '10/18/2025', 'Critical alert: Server down');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (105, null, 'debug', '4/15/2025', null);
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (118, 'critical', 'info', '11/9/2025', 'Warning: High CPU usage detected');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (115, 'medium', null, '4/15/2025', 'Information: System update available');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (107, 'low', null, '6/12/2025', 'Error: Database connection lost');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (104, 'low', 'debug', '6/9/2025', 'Information: System update available');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (92, 'medium', null, '11/3/2025', 'Information: System update available');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (116, 'critical', 'warning', '2/2/2025', 'Critical alert: Server down');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (117, null, 'warning', '5/14/2025', 'Error: Database connection lost');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (81, 'critical', 'warning', '6/5/2025', 'Error: Database connection lost');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (98, 'medium', 'critical', '10/19/2025', 'Warning: High CPU usage detected');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (91, 'critical', 'warning', '7/22/2025', 'Critical alert: Server down');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (117, null, 'critical', '9/26/2025', 'Critical alert: Server down');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (83, 'critical', null, '4/15/2025', 'Information: System update available');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (110, 'medium', 'info', '9/13/2025', 'Information: System update available');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (81, 'high', null, '12/21/2024', 'Warning: High CPU usage detected');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (120, 'critical', 'info', '9/5/2025', 'Critical alert: Server down');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (105, 'critical', 'info', '2/9/2025', 'Critical alert: Server down');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (101, 'medium', 'error', '9/1/2025', 'Information: System update available');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (85, 'medium', 'error', '12/17/2024', null);
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (103, 'low', 'critical', '3/25/2025', 'Error: Database connection lost');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (115, 'medium', 'critical', '11/27/2025', null);
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (89, 'critical', 'debug', '12/13/2024', 'Critical alert: Server down');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (110, null, 'info', '11/21/2025', 'Error: Database connection lost');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (88, 'low', 'debug', '3/20/2025', 'Critical alert: Server down');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (97, 'high', 'critical', '3/6/2025', 'Error: Database connection lost');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (105, 'low', 'error', '11/5/2025', 'Critical alert: Server down');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (103, 'medium', 'critical', '10/10/2025', null);
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (84, 'critical', 'error', '4/15/2025', 'Warning: High CPU usage detected');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (113, 'critical', 'critical', '11/1/2025', 'Error: Database connection lost');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (99, 'low', null, '1/11/2025', 'Warning: High CPU usage detected');
insert into SystemAlerts (admin_id, severity_level, notification_type, notification_time, message) values (111, 'high', 'critical', '4/10/2025', 'Information: System update available');
