insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (32, 124, 'Yoga and Meditation Plan', '4/10/2025', 'Strength training program');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (32, 151, 'Muscle Gain Program', '7/4/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (8, 135, 'Cardio Workout Routine', '5/5/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (22, 128, 'Weight Loss Plan', '5/31/2025', 'Yoga and meditation plan');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (13, 160, 'Cardio Workout Routine', '8/13/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (39, 135, 'Muscle Gain Program', '1/31/2025', 'HIIT workout routine');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (25, 141, 'High Intensity Interval Training', '4/11/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (15, 126, 'Muscle Gain Program', '2/1/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (19, 143, 'Weight Loss Plan', '1/28/2025', 'Cardio-focused workout plan');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (19, 150, 'Yoga and Meditation Plan', '8/11/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (21, 121, 'Cardio Workout Routine', '7/19/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (38, 144, 'Yoga and Meditation Plan', '4/9/2025', 'HIIT workout routine');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (29, 146, 'Cardio Workout Routine', '3/8/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (2, 128, 'Weight Loss Plan', '9/16/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (27, 155, 'Muscle Gain Program', '7/19/2025', 'Cardio-focused workout plan');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (24, 148, 'Muscle Gain Program', '6/26/2025', 'CrossFit challenge');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (14, 125, 'Weight Loss Plan', '3/27/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (21, 158, 'Cardio Workout Routine', '1/27/2025', 'Cardio-focused workout plan');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (33, 159, 'Muscle Gain Program', '6/11/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (26, 124, 'Cardio Workout Routine', '5/22/2025', 'Strength training program');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (11, 150, 'Cardio Workout Routine', '1/2/2025', 'Cardio-focused workout plan');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (30, 132, 'Yoga and Meditation Plan', '1/26/2025', 'HIIT workout routine');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (14, 155, 'High Intensity Interval Training', '11/4/2025', 'CrossFit challenge');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (18, 159, 'Muscle Gain Program', '4/3/2025', 'Cardio-focused workout plan');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (37, 143, 'Yoga and Meditation Plan', '6/30/2025', 'CrossFit challenge');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (7, 150, 'Cardio Workout Routine', '1/11/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (19, 137, 'Cardio Workout Routine', '8/23/2025', 'Strength training program');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (10, 139, 'Yoga and Meditation Plan', '8/27/2025', 'CrossFit challenge');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (34, 148, 'Yoga and Meditation Plan', '11/11/2025', 'Strength training program');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (26, 136, 'High Intensity Interval Training', '1/21/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (37, 143, 'Muscle Gain Program', '7/1/2025', 'Yoga and meditation plan');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (7, 138, 'High Intensity Interval Training', '4/6/2025', 'Strength training program');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (9, 129, 'Weight Loss Plan', '2/26/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (28, 155, 'Cardio Workout Routine', '8/26/2025', 'CrossFit challenge');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (17, 136, 'Muscle Gain Program', '8/13/2025', 'HIIT workout routine');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (4, 151, 'Weight Loss Plan', '6/3/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (31, 139, 'Cardio Workout Routine', '2/9/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (16, 155, 'Yoga and Meditation Plan', '5/6/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (31, 135, 'Muscle Gain Program', '12/31/2024', 'Strength training program');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (30, 152, 'Weight Loss Plan', '7/29/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (15, 144, 'Cardio Workout Routine', '12/17/2024', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (5, 125, 'Muscle Gain Program', '9/10/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (36, 122, 'High Intensity Interval Training', '2/17/2025', 'Yoga and meditation plan');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (13, 134, 'Muscle Gain Program', '3/26/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (40, 156, 'Cardio Workout Routine', '1/27/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (25, 141, 'Weight Loss Plan', '2/24/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (16, 127, 'Weight Loss Plan', '7/20/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (39, 159, 'Yoga and Meditation Plan', '1/25/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (10, 159, 'Cardio Workout Routine', '2/25/2025', 'Yoga and meditation plan');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (27, 124, 'Yoga and Meditation Plan', '12/29/2024', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (40, 160, 'Muscle Gain Program', '6/7/2025', 'Cardio-focused workout plan');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (33, 148, 'Weight Loss Plan', '7/10/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (7, 152, 'Weight Loss Plan', '10/16/2025', 'CrossFit challenge');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (39, 157, 'High Intensity Interval Training', '5/14/2025', 'Yoga and meditation plan');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (14, 130, 'High Intensity Interval Training', '7/4/2025', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (19, 154, 'Muscle Gain Program', '7/5/2025', 'Cardio-focused workout plan');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (2, 134, 'High Intensity Interval Training', '12/27/2024', null);
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (7, 133, 'Cardio Workout Routine', '12/6/2024', 'HIIT workout routine');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (23, 152, 'High Intensity Interval Training', '1/20/2025', 'Cardio-focused workout plan');
insert into WorkoutPlans (coach_id, client_id, plan_name, created_at, description) values (27, 142, 'Weight Loss Plan', '1/15/2025', 'Yoga and meditation plan');
