insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (52, 53, '1/6/2025', 'Drink more water', 'requirement');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (63, 17, '8/18/2025', 'Reduce sugar consumption', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (67, 22, '5/14/2025', null, 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (46, 5, '7/11/2025', 'Drink more water', null);
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (65, 19, '8/17/2025', 'Reduce sugar consumption', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (69, 31, '6/1/2025', 'Eat more fruits and vegetables', 'suggestion');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (65, 4, '9/24/2025', 'Eat more fruits and vegetables', 'requirement');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (44, 43, '2/20/2025', 'Eat more fruits and vegetables', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (60, 30, '11/2/2025', null, null);
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (68, 16, '4/17/2025', 'Eat more fruits and vegetables', 'positive');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (67, 46, '4/13/2025', 'Reduce sugar consumption', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (76, 45, '7/22/2025', 'Reduce sugar consumption', 'suggestion');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (68, 45, '6/20/2025', 'Reduce sugar consumption', 'suggestion');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (58, 10, '2/10/2025', 'Eat more fruits and vegetables', null);
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (74, 19, '1/11/2025', 'Increase fiber intake', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (62, 19, '8/31/2025', 'Increase fiber intake', 'positive');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (54, 69, '5/14/2025', null, null);
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (73, 62, '2/2/2025', 'Reduce sugar consumption', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (49, 48, '10/23/2025', null, 'suggestion');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (79, 7, '12/10/2024', null, 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (71, 22, '2/16/2025', 'Reduce sugar consumption', 'positive');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (70, 34, '9/27/2025', null, 'requirement');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (49, 15, '10/7/2025', 'Eat more fruits and vegetables', 'requirement');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (55, 12, '6/14/2025', 'Limit processed foods', 'positive');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (46, 14, '7/12/2025', 'Drink more water', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (54, 67, '2/7/2025', 'Increase fiber intake', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (48, 42, '7/15/2025', null, 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (72, 18, '10/18/2025', 'Drink more water', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (50, 20, '5/23/2025', 'Drink more water', 'positive');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (76, 50, '11/26/2025', 'Increase fiber intake', 'requirement');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (46, 52, '4/24/2025', null, null);
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (64, 36, '2/23/2025', 'Reduce sugar consumption', null);
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (74, 2, '5/8/2025', null, 'requirement');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (61, 10, '12/2/2025', 'Eat more fruits and vegetables', 'positive');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (42, 44, '9/13/2025', null, 'requirement');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (51, 52, '4/25/2025', 'Eat more fruits and vegetables', null);
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (72, 22, '9/15/2025', null, 'requirement');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (44, 27, '9/9/2025', 'Reduce sugar consumption', null);
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (51, 33, '3/12/2025', 'Drink more water', 'suggestion');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (80, 54, '8/27/2025', 'Eat more fruits and vegetables', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (76, 66, '2/15/2025', 'Drink more water', 'requirement');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (63, 59, '3/1/2025', 'Reduce sugar consumption', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (76, 27, '2/13/2025', 'Limit processed foods', 'positive');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (62, 40, '11/2/2025', 'Reduce sugar consumption', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (71, 12, '8/19/2025', 'Eat more fruits and vegetables', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (67, 51, '2/4/2025', 'Limit processed foods', 'requirement');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (62, 23, '8/23/2025', null, 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (42, 48, '4/17/2025', 'Drink more water', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (72, 31, '10/25/2025', 'Increase fiber intake', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (57, 24, '9/25/2025', null, 'positive');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (42, 13, '2/13/2025', 'Reduce sugar consumption', 'positive');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (79, 1, '3/23/2025', null, 'requirement');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (64, 62, '10/26/2025', 'Eat more fruits and vegetables', null);
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (56, 3, '9/28/2025', 'Reduce sugar consumption', 'positive');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (72, 34, '8/23/2025', 'Reduce sugar consumption', 'requirement');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (69, 56, '6/27/2025', 'Reduce sugar consumption', 'positive');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (52, 12, '10/15/2025', 'Limit processed foods', 'suggestion');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (80, 12, '9/21/2025', 'Eat more fruits and vegetables', 'negative');
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (58, 34, '6/19/2025', 'Eat more fruits and vegetables', null);
insert into Comments (dietitian_id, meal_id, comment_time, comment_text, comment_type) values (46, 23, '7/11/2025', 'Reduce sugar consumption', 'positive');
